name: 'focusbe deplay action'
description: 'deplay type'
inputs:
  project-type: 
    description: 'type of project ,front-static|front-build|npm|backend-php|backend-node'
    required: true
    default: 'front-build'
  deploy-type: 
    descrition: 'type of deploy ,example:rsync|ssh|ftp'
    required: true
    default: 'rsync'
  ip: 
    descrition: 'server ip'
    required: true
    default: ''
  username: 
    descrition: 'server username'
    required: true
    default: ''
  password: 
    descrition: 'password of username'
    required: true
    default: ''
  remote-path: 
    descrition: 'remote path'
    required: true
    default: ''
  port: 
    descrition: 'ftp port'
    required: true
    default: '21'
outputs:
  res: 
    description: 'result msg'
runs:
  using: 'node12'
  main: 'index.js'