name: 'focusbe deplay action'
description: 'deplay web-front/php/nodejs/npm tools'
inputs:
  project-type: 
    description: 'type of project ,web-static|web-build|npm|php'
    required: true
    default: ''
  deploy-type: 
    descrition: 'type of deploy ,rsync|ssh|ftp'
    required: true
    default: 'ssh'
  ip: 
    descrition: 'server ip'
    required: true
    default: ''
  username: 
    descrition: 'server username'
    required: true
    default: ''
  password: 
    descrition: 'password of username'
    required: true
    default: ''
  project-path: 
    descrition: 'project path'
    required: true
    default: ''
  output: 
    descrition: 'web front dist path'
    required: true
    default: 'dist'
outputs:
  res: 
    description: 'result msg'
runs:
  using: 'node12'
  main: 'index.js'